### PR TITLE
Init package

### PR DESCRIPTION
**Pull request by TiagoDanin**
# TO-DO
- [x] Package
- [x] Docs
- [x] Install via PIP 
- [x] Example file

# Summary
- Similar structure of my package in [node](https://github.com/TiagoDanin/node-orgmanager-api)
- Tested only in Python3.*

### CODE REVIEW

**Review by m1guelpf — APPROVED** [review]

**Comment by m1guelpf** [comment]
@TiagoDanin Looks good! What's the next step?

**Comment by TiagoDanin** [comment]
@m1guelpf Done! :)

**Comment by m1guelpf** [comment]
@TiagoDanin Is this ready to merge? Also, how do I submit it to PIP?

**Comment by TiagoDanin** [comment]
@m1guelpf  Yes, all checked and ready.
Testing with Python 2.7 and Python3.*

**Comment by TiagoDanin** [comment]
If you want I can move the [node-orgmanager-api](https://github.com/TiagoDanin/node-orgmanager-api) to the organization.

**Comment by m1guelpf** [comment]
@TiagoDanin Yeah, transfer it and I'll add you as the mantainer. Also, how can I submit this to the pip index?

**Comment by TiagoDanin** [comment]
Create a file in `~/.pypirc` [[example file]](https://github.com/TiagoDanin/dotfiles/blob/master/.pypirc) and run `python setup.py sdist upload`

**Comment by TiagoDanin** [comment]
I am not allowed of move the node-Orgmanager-API to organization.
I put you on repo for transfer. Do you have an account on NPM?

**Comment by m1guelpf** [comment]
https://github.com/TiagoDanin/node-orgmanager-api/issues/2

**Pull request merged**
